### ISSUE TITLE
Consider creating a repository to share github workflows across the Altinn organization

### ISSUE THREAD

**Issue by arealmaas** [Altinn/architecture-decision-log#34]
### Introduction
To ensure an extra layer of security and reusability, we could introduce a repository for shared workflows. 

### Description
Some workflows are used in multipole repositories. One such workflow might be registering a deployment to Swarmia. Adding these workflows in a `.github` repository allows for reuse. To take it one step further we could also create templates with actions that ensure security is implemented. 

https://docs.github.com/en/actions/administering-github-actions/sharing-workflows-secrets-and-runners-with-your-organization

https://docs.github.com/en/actions/sharing-automations/creating-workflow-templates-for-your-organization

Considerations:
- Who owns it
- We need to ensure we use parameters heavily in order to not suddenly update node-versions or similar that might break workflow for others. 
- We should probably use release tags to ensure that we do not break anything unexpectedly: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow

### Implementation
Add the swarmia workflow to `.github` repository for starters

### Tasks
- [ ] TODO

### Threat Modelling
- [ ] I have considered potential security risks (if risks were found, please list them below)

### Acceptance criteria
_GIVEN_ new workflow
_WHEN_ an existing workflow exist in the organization
_THEN_ we should be able to reuse that workflow

**Comment by elsand** [comment]
@tjololo @altinnadmin Thoughts?

**Comment by altinnadmin** [comment]
Why do we need a custom GitHub workflow for Swarmia? 🤔

**Comment by MagnusSandgren** [comment]
Refinemenet 23.04:
Dialogporten could be the first contributor to this. However, there are a couple of considerations:
- Who should own this? 
- Needs some documentation.
- Support for new functionality?

More teams needs to have a say in this as well.

**Comment by arealmaas** [comment]
Vi har implementert en workflow for Swarmia for å kunne sende status direkte til Swarmia istedenfor å koble deployments til Github-deployments, ref: https://digdir.atlassian.net/wiki/spaces/~6205262fa29402006879a50f/pages/3100573698/Swarmia+for+DORA+metrics+og+annen+stats+fra+teamene#Tips

Tanken med å skille dette ut til en workflow på organisasjonsnivå var: 
- Om API skulle endre seg, har vi mulighet til å endre dette ett sted
- Vi har mulighet til å legge på ekstra sikkerhet og best-practice konfigurasjon av github actions

For å sikre at vi ikke går i beina på hverandre så burde vi ha versjonering på plass isåfall. Vi kan godt komme med de to første PRene. Swarmia-workflow og oppsett for automatisk versjonering. Må jo specces litt først. 

Dette kan gjelde flere typer workflows også. Bruker jo mye av de samme workflowsene i digdir. Ett eksempel er den check-for-changes som opplevde en [svært alvorlig bug](https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066) for en stund siden. 

Om det er en case av unødvendig sentralisering kan jo hende, men ser noen gevinster sikkerhetsmessig. 

``` yaml
# this workflow is taken from the Swarmia docs: https://help.swarmia.com/sending-deployment-information-to-swarmia
name: Send deployment to Swarmia Deployment API

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      environment:
        required: true
        type: string
      version:
        required: false
        type: string
        default: ${{ github.sha }}
    secrets:
      token:
        required: true

jobs:
  send-deployment-to-swarmia:
    runs-on: ubuntu-latest
    steps:
    - name: Send deployment to Swarmia
      run: |
        JSON_STRING=$( jq --null-input --compact-output \
          --arg version "${{ inputs.version }}" \
          --arg appName "${{ inputs.app-name }}" \
          --arg environment "${{ inputs.environment }}" \
          --arg commitSha "${{ github.sha }}" \
          --arg repositoryFullName "${{ github.repository }}" \
          '{"version": $version, "appName": $appName, "environment": $environment, "commitSha": $commitSha, "repositoryFullName": $repositoryFullName}' )

        curl -H "Authorization: ${{ secrets.token }}" \
          -H "Content-Type: application/json" \
          -d "$JSON_STRING" \
          https://hook.swarmia.com/deployments
```
